package by.htp.newsproject.controller;

public enum CommandName {

	GO_TO_AUTHRIZATION_PAGE, GO_TO_SIGNUP_PAGE, GO_TO_ERROR_PAGE, GO_TO_BASIC_LAYOUT, GO_TO_ADD_NEWS_PAGE,
	GO_TO_EDIT_NEWS_PAGE, GO_TO_VIEW_ONE_NEWS_PAGE, GO_TO_PORTION_NEWS_PAGE,

	SIGNOUT, AUTHORIZE, SIGNUP,

	SAVE_NEWS, CANCEL_SAVE_NEWS, EDIT_NEWS, DELETE_NEWS,
	
	CHANGE_LOCALE

}
